name: Setup Environment
description: UDS Environment Setup

inputs:
  username:
    description: Registry1 user
    required: true
  password:
    description: Registry1 PW
    required: true

runs:
  using: composite
  steps:
    - name: Install k3d
      shell: bash
      # renovate: datasource=github-tags depName=k3d-io/k3d versioning=semver
      run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.6.0 bash

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install UDS CLI
      shell: bash
      # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
      run: brew install defenseunicorns/tap/uds@0.9.3

      # - name: Login to registry1
      #   env:
      #     REGISTRY: registry1.dso.mil
      #     REGISTRY_USERNAME: ${{ inputs.username }}
      #     REGISTRY_PASSWORD: ${{ inputs.password }}
      #     REGISTRY_RETRY_INTERVAL: "5"
      #   run: |
      #     uds run registry-login

    - name: Iron Bank Login
      env:
        REGISTRY_USERNAME: ${{ inputs.username }}
        REGISTRY_PASSWORD: ${{ inputs.password }}
      run: uds zarf tools registry login -u "${{ env.REGISTRY_USERNAME }}" -p "${{ env.REGISTRY_PASSWORD }}" registry1.dso.mil
      shell: bash
