tasks:
  - name: clean-runner
    description: Free GH Runner space
    actions:
      - description: Free GH Runner space
        cmd: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h