variables:
  - name: FLAVOR
    default: upstream

tasks:
  - name: package
    description: Create the UDS Zarf Package
    inputs:
      options:
        description: For setting create time variables and flags
    actions:
      - cmd: uds zarf package create --confirm --no-progress --architecture=${ZARF_ARCHITECTURE} --flavor ${FLAVOR} ${{ .inputs.options }}

  - name: test-bundle
    description: Create the test UDS Bundle
    actions:
      - cmd: uds create bundle --confirm --no-progress --architecture=${UDS_ARCH}
