tasks:
  - name: package
    inputs:
      options:
        description: "For setting deploy time variables and flags"
    actions:
      - description: Deploy the UDS Zarf Package
        cmd: uds zarf package deploy zarf-package-*-${UDS_ARCH}-*.tar.zst --confirm --no-progress ${{ .inputs.options }}

  - name: test-bundle
    actions:
      - description: Deploy the UDS bundle with the package and its dependencies
        cmd: UDS_CONFIG=bundle/uds-config.yaml uds deploy bundle/uds-bundle-*-${UDS_ARCH}-*.tar.zst --confirm --no-progress
