variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: "The version of the package to build, should be version controlled by release-please"

  - name: FLAVOR
    default: "upstream"

tasks:
  - name: package
    description: Publish the packages
    actions:
      - description: Publish the packages
        cmd: |
          set -e
          zarf package publish zarf-package-*-amd64-${VERSION}.tar.zst ${TARGET_REPO}
          if [ ${FLAVOR} != "registry1" ]; then
           zarf package publish zarf-package-*-arm64-${VERSION}.tar.zst ${TARGET_REPO}
          fi
          set +e
