variables:
  - name: REGISTRY1_TEST_IMAGE
    default: "registry1.dso.mil/ironbank/opensource/defenseunicorns/zarf/zarf-agent"
  - name: REGISTRY
    default: "${REGISTRY}"
  - name: REGISTRY_USERNAME
    default: "${REGISTRY_USERNAME}"
  - name: REGISTRY_PASSWORD
    default: "${REGISTRY_PASSWORD}"
  - name: REGISTRY_RETRY_INTERVAL
    default: "${REGISTRY_RETRY_INTERVAL}"

tasks:
  - name: create-k3d-cluster
    actions:
      - description: "Create the K3d cluster"
        # renovate: datasource=github-tags depName=defenseunicorns/uds-k3d versioning=semver
        cmd: "uds zarf package deploy oci://defenseunicorns/uds-k3d:0.3.1 --confirm"

  - name: k3d-test-cluster
    actions:
      - task: create-k3d-cluster

      - description: "Initialize the cluster with Zarf"
        # renovate: datasource=github-tags depName=defenseunicorns/init versioning=semver
        cmd: "uds zarf package deploy oci://defenseunicorns/init:v0.32.1 --confirm"

  - name: k3d-istio-test-cluster
    actions:
      - description: Create k3d cluster with UDS Core Istio
        # renovate: datasource=github-tags depName=defenseunicorns/uds-core versioning=semver
        cmd: "uds deploy oci://defenseunicorns/uds/bundles/k3d-core-istio-dev:0.10.0-${UDS_ARCH} --confirm --no-progress"

  - name: registry-login
    actions:
      - cmd: |
          echo "${REGISTRY_PASSWORD}" | uds zarf tools registry login \
            --username "${REGISTRY_USERNAME}" \
            --password-stdin \
            "${REGISTRY}" \
            >/dev/null

          if [ "${REGISTRY}" = "registry1.dso.mil" ]; then
             uds zarf tools registry digest \
               "${REGISTRY1_TEST_IMAGE}" \
               >/dev/null || (sleep "${REGISTRY_RETRY_INTERVAL}"; exit 1)
          fi 
        maxRetries: 10

