variables:
  - name: REGISTRY1_TEST_IMAGE
    default: "registry1.dso.mil/ironbank/opensource/defenseunicorns/zarf/zarf-agent"

tasks:
  - name: k3d-test-cluster
    actions:
      - description: Create k3d cluster with UDS Core Istio
        # renovate: datasource=github-tags depName=defenseunicorns/uds-core versioning=semver
        cmd: uds deploy oci://defenseunicorns/uds/bundles/k3d-core-istio-dev:0.10.0-${UDS_ARCH} --confirm --no-progress

  - name: registry-login
    inputs:
      registry:
        default: ${REGISTRY}
        description: "Registry"
      registryUsername:
        default: ${REGISTRY_USERNAME}
        description: "Registry username"
      registryPassword:
        default: ${REGISTRY_PASSWORD}
        description: "Registry password"
      registryRetryInterval:
        default: ${REGISTRY_RETRY_INTERVAL}
        description: "Registry retry interval"
    actions:
      - cmd: |
          echo ${{ .inputs.registryPassword }} | \
            uds zarf tools registry login \
            --username ${{ .inputs.registryUsername }} \
            --password-stdin ${{ .inputs.registry }} \
            >/dev/null

          if [ ${{ .inputs.registry }} = "registry1.dso.mil" ]; then
            uds zarf tools registry digest "${REGISTRY1_TEST_IMAGE}" >/dev/null || \
            (sleep ${{ .inputs.registryRetryInterval }}; exit 1)
          fi 
        maxRetries: 10

