name: Test Tasks

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]

# env:
#   flavors: ${{ inputs.flavors || 'test' }}
#  flavors: ${{ inputs.flavors == null && 'test' || inputs.flavors }}

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  id-token: write # Needed for OIDC-related operations.
  contents: read # Allows reading the content of the repository.
  pull-requests: read # Allows reading pull request metadata.

jobs:
  run-test:
    name: Create and Deploy Flavor ${{ matrix.flavor }}
    runs-on: ubuntu-latest #todo: this needs to be variable for workflow
    timeout-minutes: 20
    strategy:
      matrix:
        flavor: ${{ inputs.flavors || 'test' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Clean Runner
        uses: ./.github/actions/clean-runner

      - name: Environment setup
        uses: ./.github/actions/setup

      - name: Login to registry1
        env:
          REGISTRY: registry1.dso.mil
          REGISTRY_USERNAME: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          REGISTRY_RETRY_INTERVAL: "5"
        run: |
          uds run registry-login

      - name: Login to ghcr
        env:
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: dummy
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_RETRY_INTERVAL: "5"
        run: |
          uds run registry-login

      - name: Create test package
        run: uds run create-package --set FLAVOR=${{ matrix.flavor }}

      - name: Create test bundle
        run: uds run create-test-bundle --set FLAVOR=${{ matrix.flavor }}

      - name: Setup cluster
        run: uds run setup-cluster

      - name: Deploy test bundle
        run: uds run deploy-test-bundle

      - name: Validate tasks performed as expected
        run: uds run validate-tasks

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: ${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
